# Generated by Django 2.1.3 on 2018-11-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='账号'),
        ),
    ]
