# Generated by Django 2.1.3 on 2018-11-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globuser', '0004_auto_20181109_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(verbose_name='登陆状态'),
        ),
    ]
