# Generated by Django 2.1.3 on 2018-11-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globuser', '0005_auto_20181109_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1, verbose_name='登陆状态'),
        ),
    ]
